import { FurnitureItem } from './types';

export const furnitureDatabase: FurnitureItem[] = [
    // Living Room - Seating
    { id: 'armchair_small', name: 'Armchair Small', volume: 1.5, category: 'Living Room', icon: '🪑', image: '/images/tools-item/small_armchair.jpg' },
    { id: 'armchair_medium', name: 'Armchair Medium', volume: 1.8, category: 'Living Room', icon: '🪑', image: '/images/tools-item/medium_armchair.jpg' },
    { id: 'armchair_large', name: 'Armchair Large', volume: 2.2, category: 'Living Room', icon: '🪑', image: '/images/tools-item/large_armchair.jpg' },
    { id: 'armchair_recliner', name: 'Armchair Recliner', volume: 2.5, category: 'Living Room', icon: '🪑', image: '/images/tools-item/reclining_armchair.jpg' },
    { id: 'sofa_2seater', name: 'Sofa 2 Seater', volume: 2.5, category: 'Living Room', icon: '🛋️', image: '/images/tools-item/sofa_small.jpg' },
    { id: 'sofa_3seater', name: 'Sofa 3 Seater', volume: 3.2, category: 'Living Room', icon: '🛋️', image: '/images/tools-item/medium_sofa.jpg' },
    { id: 'sofa_4seater', name: 'Sofa 4 Seater', volume: 4.0, category: 'Living Room', icon: '🛋️', image: '/images/tools-item/large_sofa.jpg' },
    { id: 'sofa_bed', name: 'Sofa Bed', volume: 3.0, category: 'Living Room', icon: '🛋️', image: '/images/tools-item/Sofa-bed.jpg' },
    { id: 'chaise_longue', name: 'Chaise Longue', volume: 2.8, category: 'Living Room', icon: '🛋️', image: '/images/tools-item/chaise-longue.jpg' },
    { id: 'futon', name: 'Futon', volume: 2.0, category: 'Living Room', icon: '🛋️', image: '/images/tools-item/futon.jpg' },
    { id: 'chair_rocking', name: 'Chair Rocking', volume: 1.5, category: 'Living Room', icon: '🪑', image: '/images/tools-item/rocking_chair.jpg' },
    { id: 'footstool', name: 'Footstool', volume: 0.6, category: 'Living Room', icon: '🪑', image: '/images/tools-item/footstool.jpg' },
    { id: 'ottoman_box', name: 'Ottoman Box', volume: 0.8, category: 'Living Room', icon: '🪑', image: '/images/tools-item/ottoman-box.jpg' },
    
    // Living Room - Tables & Storage  
    { id: 'coffee_table', name: 'Coffee Table', volume: 0.8, category: 'Living Room', icon: '🪑', image: '/images/tools-item/coffee_table.jpg' },
    { id: 'small_table', name: 'Small Table', volume: 0.5, category: 'Living Room', icon: '🪑', image: '/images/tools-item/small-table.jpg' },
    { id: 'hall_table', name: 'Hall Table', volume: 0.7, category: 'Living Room', icon: '🪑', image: '/images/tools-item/hall_table.jpg' },
    { id: 'nest_of_tables', name: 'Nest of Tables', volume: 0.6, category: 'Living Room', icon: '🪑', image: '/images/tools-item/nest_of_tables.jpg' },
    { id: 'tv_stand', name: 'TV Stand', volume: 1.2, category: 'Living Room', icon: '📺', image: '/images/tools-item/tvstand.jpg' },
    { id: 'bookcase_small', name: 'Bookcase Small', volume: 1.0, category: 'Living Room', icon: '📚', image: '/images/tools-item/small-bookcase.jpg' },
    { id: 'bookcase_short', name: 'Bookcase Short', volume: 1.5, category: 'Living Room', icon: '📚', image: '/images/tools-item/short_bookcase.jpg' },
    { id: 'bookcase_tall', name: 'Bookcase Tall', volume: 2.5, category: 'Living Room', icon: '📚', image: '/images/tools-item/bookcase_tall.jpg' },
    { id: 'cabinet_small', name: 'Cabinet Small', volume: 1.2, category: 'Living Room', icon: '🗄️', image: '/images/tools-item/small_oak_cabinet.jpg' },
    { id: 'cabinet_medium', name: 'Cabinet Medium', volume: 1.8, category: 'Living Room', icon: '🗄️', image: '/images/tools-item/medium_oak_cabinet.jpg' },
    { id: 'cabinet_large', name: 'Cabinet Large', volume: 2.5, category: 'Living Room', icon: '🗄️', image: '/images/tools-item/large_cabinet.jpg' },
    { id: 'cd_tower', name: 'CD Tower', volume: 0.4, category: 'Living Room', icon: '💿', image: '/images/tools-item/cd-tower.jpg' },
    { id: 'hi_fi', name: 'Hi Fi', volume: 0.8, category: 'Living Room', icon: '🔊', image: '/images/tools-item/hifi.jpg' },
    { id: 'hi_fi_speaker', name: 'Hi Fi Speaker', volume: 0.3, category: 'Living Room', icon: '🔊', image: '/images/tools-item/hifi-speaker.jpg' },
    { id: 'satellite_box', name: 'Satellite/Freeview Box', volume: 0.1, category: 'Living Room', icon: '📺', image: '/images/tools-item/satellite_box.jpg' },
    { id: 'vcr_dvd', name: 'VCR/DVD/BluRay', volume: 0.15, category: 'Living Room', icon: '📀', image: '/images/tools-item/vcr-player.jpg' },
    
    // Bedroom - Beds
    { id: 'bed_divan_single', name: 'Bed Divan Single', volume: 2.0, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/single_bed_divan.jpg' },
    { id: 'bed_divan_double', name: 'Bed Divan Double', volume: 2.8, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/double_divan.jpg' },
    { id: 'bed_divan_queen', name: 'Bed Divan Queen Size', volume: 3.2, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/divan_queen_size.jpg' },
    { id: 'bed_divan_king', name: 'Bed Divan King Size', volume: 3.8, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/king_size_divan.jpg' },
    { id: 'bed_frame_single', name: 'Bed Frame Single', volume: 1.8, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/single_bed_frame.jpg' },
    { id: 'bed_frame_double', name: 'Bed Frame Double', volume: 2.5, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/double-bed-frame.jpg' },
    { id: 'bed_frame_queen', name: 'Bed Frame Queen Size', volume: 3.0, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/queen-bed-frame.jpg' },
    { id: 'bed_frame_king', name: 'Bed Frame King Size', volume: 3.5, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/king-size-bed-frame.jpg' },
    { id: 'bed_bunk', name: 'Bed Bunk', volume: 3.5, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/bunk-bed.jpg' },
    { id: 'bed_small_childs', name: 'Bed Small Childs', volume: 1.5, category: 'Bedroom', icon: '🛏️', image: '/images/tools-item/child-bed.jpg' },
    { id: 'cot', name: 'Cot', volume: 1.2, category: 'Bedroom', icon: '🍼', image: '/images/tools-item/cot.jpg' },
    
    // Bedroom - Storage
    { id: 'wardrobe_single', name: 'Wardrobe Single', volume: 2.0, category: 'Bedroom', icon: '👔', image: '/images/tools-item/single-wardrobe.jpg' },
    { id: 'wardrobe_double', name: 'Wardrobe Double', volume: 3.2, category: 'Bedroom', icon: '👔', image: '/images/tools-item/double-wardrobe.jpg' },
    { id: 'wardrobe_triple', name: 'Wardrobe Triple', volume: 4.5, category: 'Bedroom', icon: '👔', image: '/images/tools-item/triple-wardrobe.jpg' },
    { id: 'chest_drawers_small', name: 'Chest of Drawers Small', volume: 1.0, category: 'Bedroom', icon: '🗄️', image: '/images/tools-item/small-chest-drawers.jpg' },
    { id: 'chest_drawers_med', name: 'Chest of Drawers Med', volume: 1.5, category: 'Bedroom', icon: '🗄️', image: '/images/tools-item/med-chest-drawers.jpg' },
    { id: 'chest_drawers_large', name: 'Chest of Drawers Large', volume: 2.0, category: 'Bedroom', icon: '🗄️', image: '/images/tools-item/large-chest-drawers.jpg' },
    { id: 'bedside_cabinet', name: 'Bedside Cabinet', volume: 0.5, category: 'Bedroom', icon: '🪑', image: '/images/tools-item/bedside-cabinet.jpg' },
    { id: 'dressing_table', name: 'Dressing Table', volume: 1.5, category: 'Bedroom', icon: '🪑', image: '/images/tools-item/dressing-table.jpg' },
    { id: 'bedroom_chair', name: 'Bedroom Chair', volume: 0.8, category: 'Bedroom', icon: '🪑', image: '/images/tools-item/contemporary-armchairs-and-accent-chairs.jpg' },
    { id: 'nursery_chest', name: 'Nursery Chest/Dresser', volume: 1.8, category: 'Bedroom', icon: '🍼', image: '/images/tools-item/Nursery ChestDresser.jpg' },
    
    // Dining Room
    { id: 'dining_table_small', name: 'Small Dining Table', volume: 1.5, category: 'Dining Room', icon: '🍽️', image: '/images/tools-item/small-meeting-table.jpg' },
    { id: 'dining_table_medium', name: 'Medium Dining Table', volume: 2.5, category: 'Dining Room', icon: '🍽️', image: '/images/tools-item/breakfast-table.jpg' },
    { id: 'dining_table_large', name: 'Large Dining Table', volume: 3.5, category: 'Dining Room', icon: '🍽️', image: '/images/tools-item/meeting_table.jpg' },
    { id: 'dining_chair', name: 'Dining Chair', volume: 0.6, category: 'Dining Room', icon: '🪑', image: '/images/tools-item/dining_chair.jpg' },
    { id: 'chair_breakfast', name: 'Chair Breakfast', volume: 0.5, category: 'Dining Room', icon: '🪑', image: '/images/tools-item/kitchen_chair.jpg' },
    { id: 'sideboard_small', name: 'Sideboard Small', volume: 1.5, category: 'Dining Room', icon: '🗄️', image: '/images/tools-item/small_sideboard.jpg' },
    { id: 'sideboard_medium', name: 'Sideboard Medium', volume: 2.2, category: 'Dining Room', icon: '🗄️', image: '/images/tools-item/sideboard_medium.jpg' },
    { id: 'sideboard_large', name: 'Sideboard Large', volume: 3.0, category: 'Dining Room', icon: '🗄️', image: '/images/tools-item/large_sideboard.jpg' },
    { id: 'welsh_dresser', name: 'Welsh Dresser', volume: 3.5, category: 'Dining Room', icon: '🗄️', image: '/images/tools-item/welsh_dresser.jpg' },
    
    // Kitchen - Appliances
    { id: 'fridge_small', name: 'Freezer or Fridge Small', volume: 1.2, category: 'Kitchen', icon: '❄️', image: '/images/tools-item/fridge-office.jpg' },
    { id: 'fridge_freezer', name: 'Fridge Freezer', volume: 2.0, category: 'Kitchen', icon: '❄️', image: '/images/tools-item/fridge-freezer.jpg' },
    { id: 'fridge_freezer_us', name: 'Fridge Freezer US Style', volume: 3.5, category: 'Kitchen', icon: '❄️', image: '/images/tools-item/american-fridge-freezer.jpg' },
    { id: 'freezer_chest', name: 'Freezer Chest', volume: 1.8, category: 'Kitchen', icon: '❄️', image: '/images/tools-item/large-chest-freezer.jpg' },
    { id: 'freezer_tall', name: 'Freezer Tall', volume: 2.5, category: 'Kitchen', icon: '❄️', image: '/images/tools-item/tall-freezer.jpg' },
    { id: 'washing_machine', name: 'Washing Machine', volume: 1.5, category: 'Kitchen', icon: '🌊', image: '/images/tools-item/washing-machine.jpg' },
    { id: 'dryer', name: 'Dryer', volume: 1.5, category: 'Kitchen', icon: '🌀', image: '/images/tools-item/dryer.jpg' },
    { id: 'dishwasher', name: 'Dishwasher', volume: 1.2, category: 'Kitchen', icon: '🍽️', image: '/images/tools-item/dishwasher.jpg' },
    { id: 'cooker_small', name: 'Cooker Small', volume: 1.5, category: 'Kitchen', icon: '🔥', image: '/images/tools-item/cooker.jpg' },
    { id: 'cooker_large', name: 'Cooker Large', volume: 2.0, category: 'Kitchen', icon: '🔥', image: '/images/tools-item/large-cooker.jpg' },
    { id: 'cooker_range', name: 'Cooker Range', volume: 2.5, category: 'Kitchen', icon: '🔥', image: '/images/tools-item/cooker-range.jpg' },
    { id: 'microwave', name: 'Microwave', volume: 0.3, category: 'Kitchen', icon: '📻', image: '/images/tools-item/microwave2.jpg' },
    { id: 'kitchen_cabinet', name: 'Kitchen Cabinet', volume: 1.5, category: 'Kitchen', icon: '🗄️', image: '/images/tools-item/kitchen-cabinet.jpg' },
    { id: 'table_breakfast', name: 'Table Breakfast', volume: 1.2, category: 'Kitchen', icon: '🍽️', image: '/images/tools-item/breakfast-table.jpg' },
    
    // Office
    { id: 'office_desk', name: 'Office Desk', volume: 1.8, category: 'Office', icon: '💻', image: '/images/tools-item/office_desk.jpg' },
    { id: 'desk_pedestal', name: 'Desk Pedestal', volume: 2.2, category: 'Office', icon: '💻', image: '/images/tools-item/desk-pedistal.jpg' },
    { id: 'computer_desk', name: 'Computer Desk', volume: 1.5, category: 'Office', icon: '🖥️', image: '/images/tools-item/computer-desk.jpg' },
    { id: 'writing_desk', name: 'Writing Desk', volume: 1.3, category: 'Office', icon: '✍️', image: '/images/tools-item/writing_desk.jpg' },
    { id: 'bureau', name: 'Bureau', volume: 1.8, category: 'Office', icon: '✍️', image: '/images/tools-item/bureau.jpg' },
    { id: 'executive_chair', name: 'Executive Chair', volume: 1.2, category: 'Office', icon: '🪑' },
    { id: 'swivel_chair', name: 'Swivel Chair', volume: 0.9, category: 'Office', icon: '🪑', image: '/images/tools-item/office-swivel.jpg' },
    { id: 'static_chair', name: 'Static Chair', volume: 0.8, category: 'Office', icon: '🪑' },
    { id: 'filing_cabinet_2', name: 'Filing Cabinet 2 Drawer', volume: 0.8, category: 'Office', icon: '🗄️', image: '/images/tools-item/filing-cab-4-drawer.jpg' },
    { id: 'filing_cabinet_4', name: 'Filing Cabinet 4 Drawer', volume: 1.5, category: 'Office', icon: '🗄️', image: '/images/tools-item/4drawer-filing.jpg' },
    { id: 'meeting_table', name: 'Meeting Table', volume: 3.0, category: 'Office', icon: '🪑', image: '/images/tools-item/meeting_table.jpg' },
    
    // Electronics
    { id: 'tv_flat_small', name: 'TV Flat Screen Small', volume: 0.3, category: 'Electronics', icon: '📺', image: '/images/tools-item/small_flatscreen.jpg' },
    { id: 'tv_flat_large', name: 'TV Flat Screen Large', volume: 0.8, category: 'Electronics', icon: '📺', image: '/images/tools-item/large_flatscreen.jpg' },
    { id: 'tv_tube_small', name: 'TV Tube Small', volume: 0.5, category: 'Electronics', icon: '📺', image: '/images/tools-item/small-tube-tv.jpg' },
    { id: 'tv_tube_large', name: 'TV Tube Large', volume: 1.0, category: 'Electronics', icon: '📺', image: '/images/tools-item/tv-tube-large.jpg' },
    { id: 'computer_desktop', name: 'Computer Desktop', volume: 0.4, category: 'Electronics', icon: '🖥️', image: '/images/tools-item/desktop.jpg' },
    { id: 'computer_laptop', name: 'Computer Laptop', volume: 0.05, category: 'Electronics', icon: '💻', image: '/images/tools-item/laptop.jpg' },
    { id: 'computer_monitor', name: 'Computer Monitor', volume: 0.3, category: 'Electronics', icon: '🖥️', image: '/images/tools-item/monitor.jpg' },
    { id: 'monitor_flat', name: 'Monitor Flat', volume: 0.2, category: 'Electronics', icon: '🖥️', image: '/images/tools-item/flat-monitor.jpg' },
    { id: 'printer', name: 'Printer', volume: 0.3, category: 'Electronics', icon: '🖨️', image: '/images/tools-item/HO-printer.jpg' },
    { id: 'printer_network', name: 'Printer Network', volume: 0.5, category: 'Electronics', icon: '🖨️', image: '/images/tools-item/office-netwrok-printer.jpg' },
    { id: 'photocopier', name: 'Photocopier', volume: 1.2, category: 'Electronics', icon: '🖨️', image: '/images/tools-item/photocopier.jpg' },
    { id: 'fax_machine', name: 'Fax Machine', volume: 0.3, category: 'Electronics', icon: '📠', image: '/images/tools-item/fax.jpg' },
    { id: 'server_cabinet_3ft', name: 'Server Cabinet 3ft', volume: 2.0, category: 'Electronics', icon: '🖥️', image: '/images/tools-item/Server Cabinet 3ft.jpg' },
    { id: 'server_cabinet_6ft', name: 'Server Cabinet 6ft', volume: 4.0, category: 'Electronics', icon: '🖥️', image: '/images/tools-item/Server Cabinet 6ft.jpg' },
    { id: 'hard_drive', name: 'Hard Drive', volume: 0.1, category: 'Electronics', icon: '💾', image: '/images/tools-item/Hard Drive.jpg' },
    
    // Musical Instruments
    { id: 'piano_upright', name: 'Piano Upright', volume: 4.5, category: 'Music', icon: '🎹', image: '/images/tools-item/upright_piano.jpg' },
    { id: 'piano_baby_grand', name: 'Piano Baby Grand', volume: 6.0, category: 'Music', icon: '🎹', image: '/images/tools-item/baby-grand-piano.jpg' },
    { id: 'grand_piano', name: 'Grand Piano', volume: 8.0, category: 'Music', icon: '🎹', image: '/images/tools-item/grand-piano.jpg' },
    { id: 'piano_stool', name: 'Piano Stool', volume: 0.5, category: 'Music', icon: '🎹', image: '/images/tools-item/piano_stool.jpg' },
    
    // Boxes & Storage
    { id: 'pack_2', name: 'Pack 2 (Large Box)', volume: 0.18, category: 'Storage', icon: '📦', image: '/images/tools-item/packing_box_large1.jpg' },
    { id: 'pack_6', name: 'Pack 6 (Small Box)', volume: 0.06, category: 'Storage', icon: '📦', image: '/images/tools-item/packing_box_small1.jpg' },
    { id: 'boxed_3cuft', name: 'Boxed Already 3cuft', volume: 0.085, category: 'Storage', icon: '📦', image: '/images/tools-item/Packaging_old_outer_carton_.jpg' },
    { id: 'archive_boxes', name: 'Archive Boxes', volume: 0.04, category: 'Storage', icon: '📦', image: '/images/tools-item/archive-box.jpg' },
    { id: 'suitcases', name: 'Suitcases', volume: 0.3, category: 'Storage', icon: '🧳', image: '/images/tools-item/suitcase.jpg' },
    { id: 'trunk', name: 'Trunk', volume: 0.8, category: 'Storage', icon: '🧳', image: '/images/tools-item/trunk.jpg' },
    { id: 'crates', name: 'Crates', volume: 0.15, category: 'Storage', icon: '📦', image: '/images/tools-item/office-crate.jpg' },
    { id: 'bags', name: 'Bags', volume: 0.1, category: 'Storage', icon: '👜', image: '/images/tools-item/bag.jpg' },
    
    // Garden & Outdoor
    { id: 'garden_table', name: 'Garden Table', volume: 1.5, category: 'Garden', icon: '🪑', image: '/images/tools-item/garden-table.jpg' },
    { id: 'garden_chair', name: 'Garden Chair', volume: 0.8, category: 'Garden', icon: '🪑', image: '/images/tools-item/garden-chair.jpg' },
    { id: 'stacking_chair', name: 'Stacking Chair', volume: 0.6, category: 'Garden', icon: '🪑', image: '/images/tools-item/stacking-garden-chair.jpg' },
    { id: 'folding_chair', name: 'Folding Chair', volume: 0.5, category: 'Garden', icon: '🪑', image: '/images/tools-item/folding-garden-chair.jpg' },
    { id: 'garden_bench', name: 'Garden Bench', volume: 1.2, category: 'Garden', icon: '🪑', image: '/images/tools-item/garden-bench.jpg' },
    { id: 'garden_lounger', name: 'Garden Lounger', volume: 1.5, category: 'Garden', icon: '🪑', image: '/images/tools-item/lounger.jpg' },
    { id: 'picnic_table', name: 'Picnic Table', volume: 2.0, category: 'Garden', icon: '🪑', image: '/images/tools-item/picnic-table.jpg' },
    { id: 'parasol', name: 'Parasol', volume: 0.5, category: 'Garden', icon: '☂️', image: '/images/tools-item/parasol-1.jpg' },
    { id: 'portable_bbq', name: 'Portable BBQ', volume: 1.2, category: 'Garden', icon: '🔥', image: '/images/tools-item/bbq.jpg' },
    { id: 'heater_gas', name: 'Heater Gas', volume: 0.8, category: 'Garden', icon: '🔥', image: '/images/tools-item/patio-heater.jpg' },
    { id: 'mower_elec', name: 'Mower Elec', volume: 1.0, category: 'Garden', icon: '🌱', image: '/images/tools-item/mower.jpg' },
    { id: 'mower_petrol', name: 'Mower Petrol', volume: 1.3, category: 'Garden', icon: '🌱', image: '/images/tools-item/petrol-mower.jpg' },
    { id: 'ride_on_mower', name: 'Ride on Mower', volume: 3.5, category: 'Garden', icon: '🌱', image: '/images/tools-item/ride-on-mower.jpg' },
    { id: 'strimmer', name: 'Strimmer', volume: 0.6, category: 'Garden', icon: '🌱', image: '/images/tools-item/strimmer.jpg' },
    { id: 'wheelbarrow', name: 'Wheelbarrow', volume: 0.9, category: 'Garden', icon: '🛞', image: '/images/tools-item/wheelbarrow.jpg' },
    { id: 'garden_hose', name: 'Garden Hose', volume: 0.2, category: 'Garden', icon: '💧', image: '/images/tools-item/hose.jpg' },
    { id: 'outdoor_bin', name: 'Outdoor Bin', volume: 0.5, category: 'Garden', icon: '🗑️', image: '/images/tools-item/outdoor-bin.jpg' },
    { id: 'plant_indoor', name: 'Indoor Plant', volume: 0.3, category: 'Garden', icon: '🪴', image: '/images/tools-item/Indoor Plant.jpg' },
    { id: 'plant_large', name: 'Large Plant', volume: 0.8, category: 'Garden', icon: '🌿', image: '/images/tools-item/Indoor Plant.jpg' },
    { id: 'plant_outdoor_small', name: 'Small Outdoor Plant', volume: 0.4, category: 'Garden', icon: '🌱', image: '/images/tools-item/small-outdoor-plant.jpg' },
    { id: 'plant_outdoor_medium', name: 'Medium Outdoor Plant', volume: 0.6, category: 'Garden', icon: '🌿', image: '/images/tools-item/Medium Outdoor Plant.jpg' },
    { id: 'plant_outdoor_large', name: 'Large Outdoor Plant', volume: 1.0, category: 'Garden', icon: '🌳', image: '/images/tools-item/Large Outdoor Plant.jpeg' },
    { id: 'garden_ornament', name: 'Garden Ornament', volume: 0.4, category: 'Garden', icon: '🗿' },
    
    // Garage & Tools
    { id: 'bicycle', name: 'Bicycle', volume: 1.0, category: 'Garage', icon: '🚲', image: '/images/tools-item/bike.jpg' },
    { id: 'child_bicycle', name: "Child's Bicycle", volume: 0.6, category: 'Garage', icon: '🚲', image: '/images/tools-item/child-bike.jpg' },
    { id: 'workbench', name: 'Workbench', volume: 2.5, category: 'Garage', icon: '🔨', image: '/images/tools-item/workbench.jpg' },
    { id: 'tool_case', name: 'Tool Case', volume: 0.3, category: 'Garage', icon: '🧰', image: '/images/tools-item/toolcase.jpg' },
    { id: 'tool_cabinet', name: 'Tool Cabinet', volume: 2.0, category: 'Garage', icon: '🧰', image: '/images/tools-item/tool-cabinet.jpg' },
    { id: 'ladder', name: 'Ladder', volume: 0.5, category: 'Garage', icon: '🪜', image: '/images/tools-item/ladder.jpg' },
    { id: 'step_ladder', name: 'Step Ladder', volume: 0.7, category: 'Garage', icon: '🪜', image: '/images/tools-item/step-ladder.jpg' },
    { id: 'car_roof_box', name: 'Car Roof Box', volume: 1.5, category: 'Garage', icon: '🚗', image: '/images/tools-item/roof-box.jpg' },
    { id: 'spare_tyre', name: 'Spare Tyre', volume: 0.4, category: 'Garage', icon: '🛞', image: '/images/tools-item/spare-tyre.jpg' },
    
    // Recreation & Sports
    { id: 'exercise_bike', name: 'Exercise Bike', volume: 1.5, category: 'Sports', icon: '🚴', image: '/images/tools-item/exercise-bike.jpg' },
    { id: 'running_machine', name: 'Running Machine', volume: 3.2, category: 'Sports', icon: '🏃', image: '/images/tools-item/running-machine.jpg' },
    { id: 'weights_machine', name: 'Weights Machine', volume: 2.5, category: 'Sports', icon: '🏋️', image: '/images/tools-item/weight-machine.jpg' },
    { id: 'golf_clubs', name: 'Golf Clubs Bag', volume: 0.3, category: 'Sports', icon: '⛳', image: '/images/tools-item/golf-bag.jpg' },
    { id: 'canoe', name: 'Canoe', volume: 2.5, category: 'Sports', icon: '🛶', image: '/images/tools-item/canoe.jpg' },
    { id: 'skis_snowboard', name: 'Skis Snowboard', volume: 0.5, category: 'Sports', icon: '🎿', image: '/images/tools-item/snowboard.jpg' },
    { id: 'pool_table', name: 'Pool Table', volume: 5.0, category: 'Sports', icon: '🎱', image: '/images/tools-item/pool-table.jpg' },
    { id: 'snooker_table', name: 'Snooker Table 6ft', volume: 6.0, category: 'Sports', icon: '🎱', image: '/images/tools-item/snooker-table.jpg' },
    { id: 'table_tennis', name: 'Table Tennis Table', volume: 1.5, category: 'Sports', icon: '🏓', image: '/images/tools-item/table-tennis.jpg' },
    
    // Children's Items
    { id: 'climbing_frame', name: 'Climbing Frame', volume: 4.0, category: 'Children', icon: '🧗', image: '/images/tools-item/climbing-frame.jpg' },
    { id: 'trampoline', name: 'Trampoline', volume: 3.5, category: 'Children', icon: '🤸', image: '/images/tools-item/trampoline.jpg' },
    { id: 'swing', name: 'Swing', volume: 2.0, category: 'Children', icon: '🛝', image: '/images/tools-item/swing.jpg' },
    { id: 'slide', name: 'Slide', volume: 2.5, category: 'Children', icon: '🛝', image: '/images/tools-item/slide.jpg' },
    { id: 'wendy_house', name: 'Wendy House', volume: 4.5, category: 'Children', icon: '🏠', image: '/images/tools-item/wendy-house.jpg' },
    { id: 'sandpit', name: 'Sandpit', volume: 1.5, category: 'Children', icon: '🏖️', image: '/images/tools-item/sandpit.jpg' },
    { id: 'playpen', name: 'Play Pen', volume: 1.0, category: 'Children', icon: '🍼', image: '/images/tools-item/play-pen.jpg' },
    { id: 'pushchairs', name: 'Pushchairs', volume: 0.8, category: 'Children', icon: '🍼', image: '/images/tools-item/pushchair.jpg' },
    { id: 'baby_high_chair', name: 'Baby High Chair', volume: 0.7, category: 'Children', icon: '🍼', image: '/images/tools-item/child-chair.jpg' },
    
    // Miscellaneous & Decorative
    { id: 'mirror_small', name: 'Mirror Small', volume: 0.2, category: 'Miscellaneous', icon: '🪞', image: '/images/tools-item/mirror.jpg' },
    { id: 'mirror_large', name: 'Mirror Large', volume: 0.5, category: 'Miscellaneous', icon: '🪞', image: '/images/tools-item/large-mirror.jpg' },
    { id: 'picture_small', name: 'Picture Small', volume: 0.1, category: 'Miscellaneous', icon: '🖼️', image: '/images/tools-item/small-picture.jpg' },
    { id: 'picture_large', name: 'Picture Large', volume: 0.3, category: 'Miscellaneous', icon: '🖼️', image: '/images/tools-item/large-picture.jpg' },
    { id: 'rug_small', name: 'Rug Small', volume: 0.3, category: 'Miscellaneous', icon: '🪢', image: '/images/tools-item/rug.jpg' },
    { id: 'rug_large', name: 'Rug Large', volume: 0.6, category: 'Miscellaneous', icon: '🪢', image: '/images/tools-item/large-rug.jpg' },
    { id: 'lamp_floor', name: 'Lamp Floor', volume: 0.4, category: 'Miscellaneous', icon: '💡', image: '/images/tools-item/floor_lamp.jpg' },
    { id: 'lamp_table', name: 'Table Lamp', volume: 0.2, category: 'Miscellaneous', icon: '💡', image: '/images/tools-item/side-lamp.jpg' },
    { id: 'vacuum_cleaner', name: 'Vacuum Cleaner', volume: 0.4, category: 'Miscellaneous', icon: '🧹', image: '/images/tools-item/Vacuum Cleaner.jpg' },
    { id: 'ironing_board', name: 'Ironing Board', volume: 0.3, category: 'Miscellaneous', icon: '👕', image: '/images/tools-item/ironing-board.jpg' },
    { id: 'clothes_basket', name: 'Clothes Basket', volume: 0.3, category: 'Miscellaneous', icon: '🧺', image: '/images/tools-item/clothes-basket.jpg' },
    { id: 'bin', name: 'Bin', volume: 0.2, category: 'Miscellaneous', icon: '🗑️', image: '/images/tools-item/kitchen-bin.jpg' },
    { id: 'stool', name: 'Stool', volume: 0.4, category: 'Miscellaneous', icon: '🪑', image: '/images/tools-item/stool.jpg' },
];

export const presetRoomItems: { [roomName: string]: string[] } = {
    'Hallway': ['hall_table', 'small_table', 'mirror_small', 'picture_small', 'lamp_floor', 'stool'],
    'Lounge': ['sofa_3seater', 'armchair_medium', 'coffee_table', 'tv_stand', 'bookcase_small', 'cabinet_small', 'rug_large'],
    'Kitchen': ['table_breakfast', 'dining_chair', 'fridge_freezer', 'washing_machine', 'microwave', 'freezer_chest'],
    'Dining Room': ['dining_table_medium', 'dining_chair', 'sideboard_medium', 'welsh_dresser', 'rug_small', 'chair_breakfast'],
    'Bedroom 1': ['bed_divan_double', 'wardrobe_double', 'chest_drawers_med', 'bedside_cabinet', 'dressing_table', 'bedroom_chair'],
    'Loft': ['pack_2', 'pack_6', 'suitcases', 'trunk', 'archive_boxes', 'boxed_3cuft'],
    'Garden': ['garden_bench', 'garden_chair', 'garden_table', 'portable_bbq', 'mower_elec', 'parasol'],
    'Garage': ['bicycle', 'child_bicycle', 'tool_case', 'ladder', 'workbench', 'pack_2']
};

export const truckSizes = [
    { name: 'Small Van', volume: 10, description: '1-bedroom flat or studio', icon: '🚐', price: '£80-120' },
    { name: 'Medium Van', volume: 20, description: '2-bedroom flat or small house', icon: '🚚', price: '£120-180' },
    { name: 'Large Van', volume: 35, description: '3-bedroom house', icon: '🚛', price: '£180-250' },
    { name: 'Luton Van', volume: 50, description: '4-bedroom house or large home', icon: '🚚', price: '£220-300' },
    { name: 'Removal Lorry', volume: 75, description: '5+ bedroom house or office move', icon: '🚛', price: '£300-500' }
];
